// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package controller

// Flag defines model for flag.
type Flag struct {
	// Description Description of the respective grocery flag. It can desrcibe allergies or different
	Description *string `json:"description,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the flag
	Name *string `json:"name,omitempty"`
}

// Id Identifier for Mealwhile enitites
type Id = string

// Unit defines model for unit.
type Unit struct {
	// Abbreviation Abbreviation of the unit in recipes
	Abbreviation *string `json:"abbreviation,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the unit
	Name *string `json:"name,omitempty"`
}

// CreateFlagJSONRequestBody defines body for CreateFlag for application/json ContentType.
type CreateFlagJSONRequestBody = Flag

// UpdateFlagJSONRequestBody defines body for UpdateFlag for application/json ContentType.
type UpdateFlagJSONRequestBody = Flag

// CreateUnitJSONRequestBody defines body for CreateUnit for application/json ContentType.
type CreateUnitJSONRequestBody = Unit

// UpdateUnitJSONRequestBody defines body for UpdateUnit for application/json ContentType.
type UpdateUnitJSONRequestBody = Unit
