// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package controller

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all flags
	// (GET /api/v1/flag/)
	GetFlags(ctx echo.Context) error
	// Create a new flag
	// (POST /api/v1/flag/)
	CreateFlag(ctx echo.Context) error
	// Update an existing flag
	// (PUT /api/v1/flag/)
	UpdateFlag(ctx echo.Context) error
	// Delete one flag
	// (DELETE /api/v1/flag/{id})
	DeleteFlag(ctx echo.Context, id Id) error
	// Get one flag with specified id
	// (GET /api/v1/flag/{id})
	GetFlag(ctx echo.Context, id Id) error
	// Get all groceries
	// (GET /api/v1/grocery/)
	GetGroceries(ctx echo.Context) error
	// Create a new grocery
	// (POST /api/v1/grocery/)
	CreateGrocery(ctx echo.Context) error
	// Update an existing grocery
	// (PUT /api/v1/grocery/)
	UpdateGrocery(ctx echo.Context) error
	// Delete one grocery
	// (DELETE /api/v1/grocery/{id})
	DeleteGrocery(ctx echo.Context, id Id) error
	// Get one grocery with specified id
	// (GET /api/v1/grocery/{id})
	GetGrocery(ctx echo.Context, id Id) error
	// Get all recipes
	// (GET /api/v1/recipe/)
	// TODO GetRecipes(ctx echo.Context) error
	// Create a new recipe
	// (POST /api/v1/recipe/)
	// TODO CreateRecipe(ctx echo.Context) error
	// Update an existing recipe
	// (PUT /api/v1/recipe/)
	// TODO UpdateRecipe(ctx echo.Context) error
	// Delete one recipe
	// (DELETE /api/v1/recipe/{id})
	// TODO DeleteRecipe(ctx echo.Context, id Id) error
	// Get one recipe with specified id
	// (GET /api/v1/recipe/{id})
	// TODO GetRecipe(ctx echo.Context, id Id) error
	// Get all units
	// (GET /api/v1/unit/)
	GetUnits(ctx echo.Context) error
	// Create a new unit
	// (POST /api/v1/unit/)
	CreateUnit(ctx echo.Context) error
	// Update an existing unit
	// (PUT /api/v1/unit/)
	UpdateUnit(ctx echo.Context) error
	// Delete one unit
	// (DELETE /api/v1/unit/{id})
	DeleteUnit(ctx echo.Context, id Id) error
	// Get one unit with specified id
	// (GET /api/v1/unit/{id})
	GetUnit(ctx echo.Context, id Id) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetFlags converts echo context to params.
func (w *ServerInterfaceWrapper) GetFlags(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetFlags(ctx)
	return err
}

// CreateFlag converts echo context to params.
func (w *ServerInterfaceWrapper) CreateFlag(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateFlag(ctx)
	return err
}

// UpdateFlag converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateFlag(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateFlag(ctx)
	return err
}

// DeleteFlag converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteFlag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteFlag(ctx, id)
	return err
}

// GetFlag converts echo context to params.
func (w *ServerInterfaceWrapper) GetFlag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetFlag(ctx, id)
	return err
}

// GetGroceries converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroceries(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGroceries(ctx)
	return err
}

// CreateGrocery converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGrocery(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGrocery(ctx)
	return err
}

// UpdateGrocery converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGrocery(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGrocery(ctx)
	return err
}

// DeleteGrocery converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGrocery(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteGrocery(ctx, id)
	return err
}

// GetGrocery converts echo context to params.
func (w *ServerInterfaceWrapper) GetGrocery(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGrocery(ctx, id)
	return err
}

/* TODO

// GetRecipes converts echo context to params.
func (w *ServerInterfaceWrapper) GetRecipes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRecipes(ctx)
	return err
}

// CreateRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRecipe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRecipe(ctx)
	return err
}

// UpdateRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateRecipe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateRecipe(ctx)
	return err
}

// DeleteRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteRecipe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteRecipe(ctx, id)
	return err
}

// GetRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) GetRecipe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRecipe(ctx, id)
	return err
}

*/

// GetUnits converts echo context to params.
func (w *ServerInterfaceWrapper) GetUnits(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUnits(ctx)
	return err
}

// CreateUnit converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUnit(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUnit(ctx)
	return err
}

// UpdateUnit converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUnit(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUnit(ctx)
	return err
}

// DeleteUnit converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUnit(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUnit(ctx, id)
	return err
}

// GetUnit converts echo context to params.
func (w *ServerInterfaceWrapper) GetUnit(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUnit(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/v1/flag/", wrapper.GetFlags)
	router.POST(baseURL+"/api/v1/flag/", wrapper.CreateFlag)
	router.PUT(baseURL+"/api/v1/flag/", wrapper.UpdateFlag)
	router.DELETE(baseURL+"/api/v1/flag/:id", wrapper.DeleteFlag)
	router.GET(baseURL+"/api/v1/flag/:id", wrapper.GetFlag)
	router.GET(baseURL+"/api/v1/grocery/", wrapper.GetGroceries)
	router.POST(baseURL+"/api/v1/grocery/", wrapper.CreateGrocery)
	router.PUT(baseURL+"/api/v1/grocery/", wrapper.UpdateGrocery)
	router.DELETE(baseURL+"/api/v1/grocery/:id", wrapper.DeleteGrocery)
	router.GET(baseURL+"/api/v1/grocery/:id", wrapper.GetGrocery)
	// TODO router.GET(baseURL+"/api/v1/recipe/", wrapper.GetRecipes)
	// TODO router.POST(baseURL+"/api/v1/recipe/", wrapper.CreateRecipe)
	// TODO router.PUT(baseURL+"/api/v1/recipe/", wrapper.UpdateRecipe)
	// TODO router.DELETE(baseURL+"/api/v1/recipe/:id", wrapper.DeleteRecipe)
	// TODO router.GET(baseURL+"/api/v1/recipe/:id", wrapper.GetRecipe)
	router.GET(baseURL+"/api/v1/unit/", wrapper.GetUnits)
	router.POST(baseURL+"/api/v1/unit/", wrapper.CreateUnit)
	router.PUT(baseURL+"/api/v1/unit/", wrapper.UpdateUnit)
	router.DELETE(baseURL+"/api/v1/unit/:id", wrapper.DeleteUnit)
	router.GET(baseURL+"/api/v1/unit/:id", wrapper.GetUnit)

}
