// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package controller

// Flag defines model for flag.
type Flag struct {
	// Description Description of the respective grocery flag. It can desrcibe allergies or dietries
	Description *string `json:"description,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the flag
	Name *string `json:"name,omitempty"`
}

// FlagRequest defines model for flagRequest.
type FlagRequest struct {
	// Description Description of the respective grocery flag. It can desrcibe allergies or dietries
	Description *string `json:"description,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the flag
	Name *string `json:"name,omitempty"`
}

// Grocery defines model for grocery.
type Grocery struct {
	// Flags The grocery flags contained by the grocery
	Flags *[]Flag `json:"flags,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the grocery
	Name *string `json:"name,omitempty"`
}

// GroceryRequest defines model for groceryRequest.
type GroceryRequest struct {
	// Flags The grocery flags contained by the grocery
	Flags *[]Id `json:"flags,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the grocery
	Name *string `json:"name,omitempty"`
}

// Id Identifier for Mealwhile enitites
type Id = string

// Ingredient defines model for ingredient.
type Ingredient struct {
	Amount  *float32 `json:"amount,omitempty"`
	Grocery *Grocery `json:"grocery,omitempty"`
	Unit    *Unit    `json:"unit,omitempty"`
}

// Recipe defines model for recipe.
type Recipe struct {
	// Description The description of the recipe
	Description *string `json:"description,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id          *Id           `json:"id,omitempty"`
	Ingredients *[]Ingredient `json:"ingredients,omitempty"`

	// Name The name of the recipe
	Name  *string   `json:"name,omitempty"`
	Steps *[]string `json:"steps,omitempty"`
}

// RecipeRequest defines model for recipeRequest.
type RecipeRequest struct {
	// Description The description of the recipe
	Description *string `json:"description,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id          *Id           `json:"id,omitempty"`
	Ingredients *[]Ingredient `json:"ingredients,omitempty"`

	// Name The name of the recipe
	Name  *string   `json:"name,omitempty"`
	Steps *[]string `json:"steps,omitempty"`
}

// Unit defines model for unit.
type Unit struct {
	// Abbreviation Abbreviation of the unit in recipes
	Abbreviation *string `json:"abbreviation,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the unit
	Name *string `json:"name,omitempty"`
}

// UnitRequest defines model for unitRequest.
type UnitRequest struct {
	// Abbreviation Abbreviation of the unit in recipes
	Abbreviation *string `json:"abbreviation,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the unit
	Name *string `json:"name,omitempty"`
}

// CreateFlagJSONRequestBody defines body for CreateFlag for application/json ContentType.
type CreateFlagJSONRequestBody = FlagRequest

// UpdateFlagJSONRequestBody defines body for UpdateFlag for application/json ContentType.
type UpdateFlagJSONRequestBody = FlagRequest

// CreateGroceryJSONRequestBody defines body for CreateGrocery for application/json ContentType.
type CreateGroceryJSONRequestBody = GroceryRequest

// UpdateGroceryJSONRequestBody defines body for UpdateGrocery for application/json ContentType.
type UpdateGroceryJSONRequestBody = GroceryRequest

// CreateRecipeJSONRequestBody defines body for CreateRecipe for application/json ContentType.
type CreateRecipeJSONRequestBody = RecipeRequest

// UpdateRecipeJSONRequestBody defines body for UpdateRecipe for application/json ContentType.
type UpdateRecipeJSONRequestBody = RecipeRequest

// CreateUnitJSONRequestBody defines body for CreateUnit for application/json ContentType.
type CreateUnitJSONRequestBody = UnitRequest

// UpdateUnitJSONRequestBody defines body for UpdateUnit for application/json ContentType.
type UpdateUnitJSONRequestBody = UnitRequest
