// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package controller

// Id Identifier for Mealwhile enitites
type Id = string

// Unit defines model for Unit.
type Unit struct {
	// Abbreviation Abbreviation of the unit in recipes
	Abbreviation *string `json:"abbreviation,omitempty"`

	// Id Identifier for Mealwhile enitites
	Id *Id `json:"id,omitempty"`

	// Name Name of the unit
	Name *string `json:"name,omitempty"`
}

// CreateUnitJSONRequestBody defines body for CreateUnit for application/json ContentType.
type CreateUnitJSONRequestBody = Unit

// UpdateUnitJSONRequestBody defines body for UpdateUnit for application/json ContentType.
type UpdateUnitJSONRequestBody = Unit
